name: Publish Docker

on:
  push:
    branches:
      - master

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: klsyinghua/excalidraw:latest
